/** Shared styles used across all tabs and components. */

const styles: Record<string, React.CSSProperties> = {
  container: {
    fontFamily: "'Instrument Sans', 'SF Pro Text', 'Avenir Next', sans-serif",
    maxWidth: 1600,
    margin: "0 auto",
    padding: "20px clamp(18px, 2.8vw, 40px) 34px",
    minHeight: "100vh",
    color: "var(--text-primary)",
    position: "relative",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 16,
    padding: "16px 20px",
    border: "1px solid var(--line-strong)",
    borderRadius: 20,
    background: "linear-gradient(180deg, rgba(3, 40, 33, 0.95), rgba(2, 31, 26, 0.92))",
    boxShadow: "0 24px 56px rgba(0, 21, 17, 0.56), inset 0 0 0 1px rgba(68, 181, 161, 0.18)",
    backdropFilter: "blur(14px) saturate(120%)",
    flexWrap: "wrap",
    position: "relative",
    overflow: "hidden",
  },
  headerCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  logo: {
    fontSize: "clamp(28px, 3.8vw, 44px)",
    fontWeight: 700,
    fontFamily: "'Instrument Sans', sans-serif",
    letterSpacing: "-0.04em",
    lineHeight: 1,
    background: "var(--bg-recipe-light-to-accent)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    filter: "drop-shadow(0 6px 16px rgba(68, 181, 161, 0.22))",
  },
  subtitle: {
    color: "var(--text-muted)",
    fontSize: 11,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    fontWeight: 700,
  },
  headerBadge: {
    padding: "6px 11px",
    borderRadius: 999,
    border: "1px solid var(--line-soft)",
    background: "rgba(68, 181, 161, 0.12)",
    color: "var(--text-secondary)",
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  tabs: {
    display: "flex",
    gap: 8,
    marginBottom: 18,
    flexWrap: "wrap",
    padding: "8px 8px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 16,
    background: "linear-gradient(180deg, rgba(6, 54, 46, 0.88), rgba(3, 44, 37, 0.84))",
    boxShadow: "0 18px 40px rgba(0, 25, 20, 0.42)",
    backdropFilter: "blur(10px)",
    position: "relative",
    overflowX: "auto",
  },
  tab: {
    padding: "10px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 12,
    background: "rgba(8, 58, 50, 0.6)",
    color: "var(--text-muted)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    minWidth: 112,
    whiteSpace: "nowrap",
    position: "relative",
    overflow: "hidden",
    transition: "all 0.22s cubic-bezier(0.22, 1, 0.36, 1)",
    textTransform: "uppercase",
  },
  tabActive: {
    background: "rgba(68, 181, 161, 0.2)",
    color: "var(--text-primary)",
    borderColor: "var(--line-strong)",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.08), 0 12px 28px rgba(0, 25, 20, 0.5)",
  },
  card: {
    background: "var(--surface-card)",
    borderRadius: 18,
    padding: 22,
    marginBottom: 18,
    border: "1px solid var(--line-soft)",
    boxShadow: "0 20px 42px rgba(0, 24, 19, 0.46)",
    backdropFilter: "blur(8px) saturate(120%)",
    animation: "cardReveal 0.34s ease-out both",
  },
  panelDark: {
    background: "var(--surface-panel)",
    borderRadius: 12,
    border: "1px solid var(--line-soft)",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 16,
    color: "var(--text-primary)",
    letterSpacing: "0.01em",
    display: "flex",
    alignItems: "center",
    gap: 8,
    textTransform: "uppercase",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 18,
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 10,
    background: "rgba(33, 95, 85, 0.24)",
    color: "var(--text-primary)",
    fontSize: 14,
    marginBottom: 8,
  },
  button: {
    padding: "10px 18px",
    border: "1px solid rgba(68, 181, 161, 0.72)",
    borderRadius: 10,
    background: "var(--accent-primary)",
    color: "var(--bg-primary)",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: "0.03em",
    cursor: "pointer",
    textTransform: "uppercase",
  },
  buttonPrimary: {
    padding: "10px 18px",
    border: "1px solid rgba(68, 181, 161, 0.72)",
    borderRadius: 10,
    background: "var(--accent-primary)",
    color: "var(--bg-primary)",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: "0.03em",
    cursor: "pointer",
    textTransform: "uppercase",
  },
  buttonSecondary: {
    padding: "8px 14px",
    border: "1px solid rgba(33, 95, 85, 0.72)",
    borderRadius: 10,
    background: "var(--accent-secondary)",
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  buttonSecondaryFilled: {
    padding: "8px 14px",
    border: "1px solid rgba(33, 95, 85, 0.72)",
    borderRadius: 10,
    background: "var(--accent-secondary)",
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  buttonSecondaryOutline: {
    padding: "8px 14px",
    border: "1px solid var(--line-strong)",
    borderRadius: 10,
    background: "transparent",
    color: "var(--accent-primary)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  buttonDanger: {
    padding: "8px 14px",
    border: "1px solid rgba(239, 68, 68, 0.78)",
    borderRadius: 10,
    background: "var(--semantic-error)",
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  buttonDestructive: {
    padding: "8px 14px",
    border: "1px solid rgba(239, 68, 68, 0.78)",
    borderRadius: 10,
    background: "var(--semantic-error)",
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  response: {
    background: "var(--code-surface)",
    borderRadius: 10,
    padding: 16,
    marginTop: 12,
    fontFamily: "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
    fontSize: 12,
    overflow: "auto",
    maxHeight: 400,
    border: "1px solid var(--line-soft)",
  },
  badge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    marginLeft: 8,
    border: "1px solid transparent",
  },
  badgeSuccess: {
    background: "var(--semantic-success-soft)",
    color: "var(--semantic-success)",
    borderColor: "rgba(16, 185, 129, 0.36)",
  },
  badgeError: {
    background: "var(--semantic-error-soft)",
    color: "var(--semantic-error)",
    borderColor: "rgba(239, 68, 68, 0.36)",
  },
  badgePending: {
    background: "var(--semantic-warning-soft)",
    color: "var(--semantic-warning)",
    borderColor: "rgba(245, 158, 11, 0.36)",
  },
  badgeInfo: {
    background: "var(--semantic-info-soft)",
    color: "var(--semantic-info)",
    borderColor: "rgba(59, 130, 246, 0.36)",
  },
  badgeNeutral: {
    background: "var(--semantic-neutral-soft)",
    color: "var(--semantic-neutral)",
    borderColor: "rgba(148, 163, 184, 0.34)",
  },
  chipSelected: {
    padding: "6px 12px",
    borderRadius: 999,
    border: "1px solid var(--line-strong)",
    background: "rgba(68, 181, 161, 0.24)",
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 700,
  },
  chipUnselected: {
    padding: "6px 12px",
    borderRadius: 999,
    border: "1px solid var(--line-soft)",
    background: "rgba(0, 47, 39, 0.6)",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 700,
  },
  select: {
    width: "100%",
    padding: "12px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 10,
    background: "rgba(33, 95, 85, 0.24)",
    color: "var(--text-primary)",
    fontSize: 14,
    marginBottom: 8,
  },
  label: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 4,
    display: "block",
    fontWeight: 700,
  },
  row: {
    display: "flex",
    gap: 10,
    alignItems: "flex-end",
    marginBottom: 12,
    flexWrap: "wrap",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
    marginRight: 8,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13.5,
  },
  th: {
    textAlign: "left",
    padding: "12px 10px",
    borderBottom: "1px solid var(--line-soft)",
    color: "var(--text-secondary)",
    fontWeight: 700,
  },
  td: {
    padding: "12px 10px",
    borderBottom: "1px solid rgba(68, 181, 161, 0.16)",
  },

  bgRecipeDarkToAccent: {
    background: "var(--bg-recipe-dark-to-accent)",
  },
  bgRecipeLightToAccent: {
    background: "var(--bg-recipe-light-to-accent)",
  },
};

export default styles;
