/** Shared styles used across all tabs and components. */
const styles = {
  container: {
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    maxWidth: 1400,
    margin: "0 auto",
    padding: 20,
    background: "#0a0a0a",
    minHeight: "100vh",
    color: "#e0e0e0",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: 24,
    borderBottom: "1px solid #333",
    paddingBottom: 16,
  },
  logo: {
    fontSize: 32,
    fontWeight: 700,
    background: "linear-gradient(135deg, #00d4aa, #00a8e8)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  tabs: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  tab: {
    padding: "10px 20px",
    border: "1px solid #333",
    borderRadius: 8,
    background: "#1a1a1a",
    color: "#888",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
    transition: "all 0.2s",
  },
  tabActive: {
    background: "linear-gradient(135deg, #00d4aa, #00a8e8)",
    color: "#000",
    borderColor: "transparent",
  },
  card: {
    background: "#1a1a1a",
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    border: "1px solid #2a2a2a",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 600,
    marginBottom: 16,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 16,
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    border: "1px solid #333",
    borderRadius: 6,
    background: "#0a0a0a",
    color: "#fff",
    fontSize: 14,
    marginBottom: 8,
  },
  button: {
    padding: "10px 20px",
    border: "none",
    borderRadius: 6,
    background: "linear-gradient(135deg, #00d4aa, #00a8e8)",
    color: "#000",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "transform 0.1s",
  },
  buttonSecondary: {
    padding: "8px 16px",
    border: "1px solid #444",
    borderRadius: 6,
    background: "#2a2a2a",
    color: "#fff",
    fontSize: 13,
    cursor: "pointer",
  },
  buttonDanger: {
    background: "linear-gradient(135deg, #ff4757, #ff3838)",
  },
  response: {
    background: "#0d1117",
    borderRadius: 8,
    padding: 16,
    marginTop: 12,
    fontFamily: "'Fira Code', 'Consolas', monospace",
    fontSize: 12,
    overflow: "auto",
    maxHeight: 400,
    border: "1px solid #30363d",
  },
  badge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 12,
    fontSize: 11,
    fontWeight: 600,
    marginLeft: 8,
  },
  badgeSuccess: { background: "#00d4aa22", color: "#00d4aa" },
  badgeError: { background: "#ff475722", color: "#ff4757" },
  badgePending: { background: "#ffa50022", color: "#ffa500" },
  select: {
    width: "100%",
    padding: "10px 14px",
    border: "1px solid #333",
    borderRadius: 6,
    background: "#0a0a0a",
    color: "#fff",
    fontSize: 14,
    marginBottom: 8,
  },
  label: {
    fontSize: 12,
    color: "#888",
    marginBottom: 4,
    display: "block",
  },
  row: {
    display: "flex",
    gap: 12,
    alignItems: "flex-end",
    marginBottom: 12,
    flexWrap: "wrap",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
    marginRight: 8,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    padding: "12px 8px",
    borderBottom: "1px solid #333",
    color: "#888",
    fontWeight: 500,
  },
  td: {
    padding: "12px 8px",
    borderBottom: "1px solid #222",
  },
};

export default styles;
