/** Shared styles used across all tabs and components. */
const styles = {
  container: {
    fontFamily: "'Plus Jakarta Sans', 'SF Pro Text', 'Avenir Next', sans-serif",
    maxWidth: 1480,
    margin: "0 auto",
    padding: "28px clamp(16px, 2.4vw, 34px) 34px",
    minHeight: "100vh",
    color: "var(--text-primary)",
    position: "relative",
  },
  header: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 20,
    marginBottom: 22,
    padding: "20px 22px",
    border: "1px solid var(--line-soft)",
    borderRadius: 22,
    background: "var(--surface-strong)",
    boxShadow: "var(--shadow-soft)",
    backdropFilter: "blur(14px)",
    flexWrap: "wrap",
  },
  headerCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  logo: {
    fontSize: "clamp(30px, 4vw, 40px)",
    fontWeight: 700,
    fontFamily: "'Sora', 'Plus Jakarta Sans', sans-serif",
    letterSpacing: "-0.04em",
    lineHeight: 1,
    background: "linear-gradient(136deg, var(--text-primary) 0%, var(--accent-ice) 58%, #d6eeff 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  subtitle: {
    color: "var(--text-muted)",
    fontSize: 13,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  headerBadge: {
    padding: "8px 14px",
    borderRadius: 999,
    border: "1px solid var(--line-soft)",
    background: "linear-gradient(130deg, rgba(74, 137, 255, 0.18), rgba(68, 255, 227, 0.08))",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.02em",
  },
  tabs: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
    flexWrap: "wrap",
    padding: 8,
    border: "1px solid var(--line-soft)",
    borderRadius: 16,
    background: "var(--surface-strong)",
    boxShadow: "var(--shadow-soft)",
    backdropFilter: "blur(12px)",
  },
  tab: {
    padding: "10px 16px",
    border: "1px solid transparent",
    borderRadius: 12,
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.01em",
    minWidth: 90,
    transition: "all 0.22s cubic-bezier(0.22, 1, 0.36, 1)",
  },
  tabActive: {
    background: "linear-gradient(130deg, rgba(82, 146, 255, 0.36), rgba(92, 255, 236, 0.24))",
    color: "#e9f6ff",
    borderColor: "rgba(129, 185, 255, 0.36)",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.06), 0 10px 24px rgba(7, 12, 24, 0.42)",
  },
  card: {
    background: "var(--surface-card)",
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    border: "1px solid var(--line-soft)",
    boxShadow: "var(--shadow-soft)",
    backdropFilter: "blur(9px)",
    animation: "cardReveal 0.36s ease-out both",
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: 600,
    marginBottom: 16,
    color: "var(--text-primary)",
    letterSpacing: "-0.01em",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 18,
  },
  input: {
    width: "100%",
    padding: "11px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 10,
    background: "rgba(10, 14, 24, 0.72)",
    color: "var(--text-primary)",
    fontSize: 14,
    marginBottom: 8,
  },
  button: {
    padding: "10px 18px",
    border: "1px solid rgba(133, 189, 255, 0.34)",
    borderRadius: 10,
    background: "linear-gradient(125deg, rgba(89, 147, 255, 0.95), rgba(102, 242, 252, 0.9))",
    color: "#06101f",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: "0.01em",
    cursor: "pointer",
    boxShadow: "0 12px 24px rgba(10, 20, 38, 0.45)",
  },
  buttonSecondary: {
    padding: "8px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 10,
    background: "rgba(20, 29, 46, 0.6)",
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  },
  buttonDanger: {
    background: "linear-gradient(135deg, #ff6f78, #ff8d78)",
    borderColor: "rgba(255, 160, 167, 0.42)",
    color: "#1d080c",
  },
  response: {
    background: "var(--code-surface)",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    fontFamily: "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
    fontSize: 12,
    overflow: "auto",
    maxHeight: 400,
    border: "1px solid var(--line-soft)",
  },
  badge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600,
    marginLeft: 8,
    border: "1px solid transparent",
  },
  badgeSuccess: {
    background: "rgba(70, 214, 181, 0.18)",
    color: "var(--accent-success)",
    borderColor: "rgba(91, 230, 199, 0.24)",
  },
  badgeError: {
    background: "rgba(255, 127, 136, 0.18)",
    color: "var(--accent-danger)",
    borderColor: "rgba(255, 156, 163, 0.26)",
  },
  badgePending: {
    background: "rgba(255, 185, 103, 0.18)",
    color: "var(--accent-warn)",
    borderColor: "rgba(255, 202, 140, 0.26)",
  },
  select: {
    width: "100%",
    padding: "11px 14px",
    border: "1px solid var(--line-soft)",
    borderRadius: 10,
    background: "rgba(10, 14, 24, 0.72)",
    color: "var(--text-primary)",
    fontSize: 14,
    marginBottom: 8,
  },
  label: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 4,
    display: "block",
  },
  row: {
    display: "flex",
    gap: 10,
    alignItems: "flex-end",
    marginBottom: 12,
    flexWrap: "wrap",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
    marginRight: 8,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13.5,
  },
  th: {
    textAlign: "left",
    padding: "12px 10px",
    borderBottom: "1px solid rgba(123, 149, 189, 0.26)",
    color: "var(--text-muted)",
    fontWeight: 600,
  },
  td: {
    padding: "12px 10px",
    borderBottom: "1px solid rgba(111, 138, 175, 0.16)",
  },
};

export default styles;
